Update openjfx.io
openjfx/openjfx.github.io pull request #33
Opened 2021-01-28 18:25 UTC by abhinayagarwal

Update openjfx.io with the following changes:

1. Add section for Scene Builder and TestFX
2. Add references to FXML and CSS guide
3. Add links to community documentation

Fixes #15
Fixes #31 

<img src="https://user-images.githubusercontent.com/3197675/106181722-edbc7500-61c3-11eb-87b9-8d4d85d8d4af.png" width="50%">

2021-01-28 20:50 UTC, eugener requested changes
Looks very good. Just one small change ;)
See my comment on toml file

2021-01-28 20:50 UTC, eugener commented on config.toml
> +    description = "JavaFX applications can target desktop, mobile and embedded systems. Libraries and softwares are available for the entire life-cycle of an application."
Remove s from softwares - just "software"

2021-01-29 04:22 UTC, eugener approved these changes

2021-01-29 07:15 UTC, johanvos approved these changes

2021-02-04 08:19 UTC, merged